[package]
name = "rustflare"
version = "0.1.0"
edition = "2021"

[dependencies]
acme-lib = "0.7"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
dotenv = "0.15"
