services:
  rustflare:
    image: rustflare
    container_name: rustflare
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /home/laughingman/rustflare/docker/config.yaml:/app/config.yaml:ro
      - certs:/certs

volumes:
  certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/appdata/rustflare/certs'
